Author: KISHAN MISHRA
Roll: 19
SIC : 190310106

In [1]:
import numpy as np

1. Create a null vector of size 10 but the fifth value is 1

In [2]:
vec=np.zeros(10)
vec[4]=1

print("Null vector created is :",vec)

Null vector created is : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49 

In [3]:
vec=np.arange(10,50)

print("Vector created :",vec)

Vector created : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Reverse a vector (first element becomes last)

In [4]:
vec=np.random.randint(1,10,10)
print("Original Vector: ",vec)
print("Reversed Vector:",vec[::-1])
print("Reversed Vector:",np.flipud(vec)) #np.flipud is used to reverse 1-D arrays

Original Vector:  [8 2 1 5 5 3 8 8 7 2]
Reversed Vector: [2 7 8 8 3 5 5 1 2 8]
Reversed Vector: [2 7 8 8 3 5 5 1 2 8]


4. Create a 3x3 matrix with values ranging from 0 to 8
`hint: reshape`

In [5]:
vec=np.arange(0,9).reshape(3,3)

print("Vector created :\n",vec)

Vector created :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Find indices of non-zero elements from [1,2,0,0,4,0]
`hint: np.nonzero`

In [6]:
vec=np.array([1,2,0,0,4,0])

print("Non zero elements",vec[vec>0])
print("Non zero element's indices:",np.nonzero(vec))

Non zero elements [1 2 4]
Non zero element's indices: (array([0, 1, 4]),)


6. Create a 3x3x3 array with random values
`hint: np.random.random`

In [7]:
vec=np.random.random((3,3,3))
vec

array([[[0.29599283, 0.22545848, 0.89582018],
        [0.35589047, 0.56396348, 0.67132773],
        [0.28652842, 0.03481496, 0.88316141]],

       [[0.14253043, 0.05693258, 0.26470716],
        [0.87342903, 0.02665379, 0.27775761],
        [0.51089066, 0.03170868, 0.99342841]],

       [[0.89568131, 0.32361473, 0.96917741],
        [0.41772161, 0.29007128, 0.61271685],
        [0.14543045, 0.39943942, 0.24894059]]])

7. Create a 10x10 array with random values and find the minimum and
maximum values
`hint: min, max`

In [8]:
vec=np.random.random((10,10))

print("Minimum : {} Maximum : {}".format(np.min(vec),np.max(vec)))

Minimum : 0.00041313572257406506 Maximum : 0.9911901174842561


8. Create a random vector of size 30 and find the mean value
`hint: mean`

In [9]:
vec=np.random.random((30))

print("Original Vector\n",vec)

print("\nMean of the vector:",np.mean(vec))

Original Vector
 [0.28393866 0.38588422 0.07041723 0.24366055 0.65263414 0.27409403
 0.00519373 0.80079249 0.9728565  0.11040063 0.13610245 0.76815737
 0.12617425 0.81956091 0.00755969 0.93285348 0.69842662 0.91941521
 0.09812229 0.60787669 0.10553162 0.73671578 0.12266671 0.020322
 0.47803587 0.71430724 0.61556823 0.18272016 0.85821393 0.74122236]

Mean of the vector: 0.4496475012054482


9. Create a 2d array with 1 on the border and 0 inside
`hint: array[1:-1, 1:-1]`

In [10]:
vec=np.ones((10,10))
vec[1:-1,1:-1]=0

print(vec)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


10. Normalize a 5x5 random matrix
`hint: (x -mean)/std`

In [11]:
vec=np.random.random((5,5))

print("Vector before normalized :\n",vec)

mean=np.mean(vec)
std=np.std(vec)

vec=(vec-mean)/std

print("\nVector after normalized :\n",vec)

Vector before normalized :
 [[0.56534435 0.07204362 0.18160182 0.53839901 0.58810047]
 [0.03190261 0.86631735 0.11106637 0.64551091 0.9942476 ]
 [0.59724597 0.94902911 0.10425567 0.5634483  0.34832314]
 [0.61949445 0.97113153 0.89589182 0.81608969 0.33087814]
 [0.82514345 0.51700484 0.08195879 0.89407271 0.13799162]]

Vector after normalized :
 [[ 0.1115649  -1.43939024 -1.09493534  0.02684779  0.18311095]
 [-1.56559501  1.05783478 -1.31670131  0.36361145  1.46005208]
 [ 0.21186473  1.31788352 -1.3381144   0.10560364 -0.57075756]
 [ 0.28181476  1.38737431  1.15081798  0.89991724 -0.62560527]
 [ 0.92838257 -0.04041624 -1.40821658  1.14509863 -1.23204737]]


11. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [12]:
vec=np.random.random((5,3))
vec2=np.random.random((3,2))

print(vec.dot(vec2))

[[1.23849844 0.56507386]
 [0.94928781 0.53073501]
 [0.55604215 0.39094307]
 [0.92754955 0.580304  ]
 [1.49695303 0.68450211]]


12. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [13]:
vec=np.arange(1,11)

vec[3:7]=np.multiply(vec[3:7],-1)
print(vec)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


13. Find the eigenvalues and eigenvectors of a square matrix.
`hint: np.linalg.eig`

In [14]:
vec=np.arange(1,10).reshape(3,3)
print("Original Vector: \n",vec)

print("\nEigen Matrix\n")
print(np.linalg.eig(vec))


Original Vector: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Eigen Matrix

(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


14. Find the inverse of a square matrix.
`hint: np.linalg.inv`

In [15]:
vec=np.arange(1,10).reshape(3,3)
print("Original Vector: \n",vec)

print("\nInverse of the matrix :")
print(np.linalg.inv(vec))

Original Vector: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Inverse of the matrix :
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
